export enum WIZARD_SELECTION_TYPEKEYS {
  SELECT_FRONTEND_FRAMEWORK = "WTS/wizardSelections/SELECT_FRONTEND_FRAMEWORK",
  SELECT_BACKEND_FRAMEWORK = "WTS/wizardSelections/SELECT_BACKEND_FRAMEWORK",
  SELECT_PAGES = "WTS/wizardSelections/SELECT_PAGES",
  SELECT_PAGE = "WTS/wizardSelections/SELECT_PAGE",
  SELECT_WEB_APP = "WTS/wizardSelections/SELECT_WEB_APP",
  UPDATE_PROJECT_NAME = "WTS/wizardSelections/UPDATE_PROJECT_NAME",
  UPDATE_OUTPUT_PATH = "WTS/wizardSelections/UPDATE_PROJECT_PATH",
  SET_PROJECT_PATH_VALIDATION = "WTS/wizardSelections/SET_PROJECT_PATH_VALIDATION",
  SET_VALIDATIONS = "WTS/wizardSelections/SET_VALIDATIONS",
  RESET_PAGES = "WTS/wizardSelections/RESET_PAGES"
}
