#!/bin/sh

PREFIX="pre-commit:"

cd ./src/client/
echo "$PREFIX Execute client Lint"
if ! yarn lint; then
    exit 1
fi

cd ../extension/
echo "$PREFIX Execute extension Lint"
if ! yarn lint; then
    exit 1
fi