const GET_VSCODE_API = "WTS/vscode/GET_VSCODE_API";

// Obtaining wizard data from engine
const GET_WEB_APP_OPTIONS = "WTS/wizardContent/GET_WEB_APP_OPTIONS";
const GET_WEB_APP_OPTIONS_SUCCESS = "WTS/wizardContent/GET_WEB_APP_OPTIONS_SUCCESS";
const GET_PAGES_OPTIONS_SUCCESS = "WTS/wizardContent/GET_PAGES_OPTIONS_SUCCESS";
const GET_FRONTEND_FRAMEWORKS_SUCCESS = "WTS/wizardContent/GET_FRONTEND_FRAMEWORKS_SUCCESS";
const GET_BACKEND_FRAMEWORKS_SUCCESS = "WTS/wizardContent/GET_BACKEND_FRAMEWORKS_SUCCESS";
const LOAD_WIZARD_CONTENT = "WTS/wizardContent/LOAD_WIZARD_CONTENT";

// Wizard selection actions
const SELECT_FRONTEND_FRAMEWORK = "WTS/wizardSelections/SELECT_FRONTEND_FRAMEWORK";

export { SELECT_FRONTEND_FRAMEWORK, GET_BACKEND_FRAMEWORKS_SUCCESS, GET_FRONTEND_FRAMEWORKS_SUCCESS, GET_VSCODE_API, GET_WEB_APP_OPTIONS, GET_WEB_APP_OPTIONS_SUCCESS, LOAD_WIZARD_CONTENT, GET_PAGES_OPTIONS_SUCCESS };
