const GET_VSCODE_API = "WTS/vscode/GET_VSCODE_API";
const GET_WEB_APP_OPTIONS = "WTS/wizardContent/GET_WEB_APP_OPTIONS";
const GET_WEB_APP_OPTIONS_SUCCESS = "WTS/wizardContent/GET_WEB_APP_OPTIONS_SUCCESS";
const GET_PAGES_OPTIONS_SUCCESS = "WTS/wizardContent/GET_PAGES_OPTIONS_SUCCESS";
const LOAD_WIZARD_CONTENT = "WTS/wizardContent/LOAD_WIZARD_CONTENT";

export { GET_VSCODE_API, GET_WEB_APP_OPTIONS, GET_WEB_APP_OPTIONS_SUCCESS, LOAD_WIZARD_CONTENT, GET_PAGES_OPTIONS_SUCCESS };
