
//reagrupar por request/result
export const CLI = {
  BASE_CLI_TOOL_NAME: "Microsoft.Templates.Cli",
  SYNC_COMPLETE_STATE: "syncResult",
  SYNC_PROGRESS_STATE: "syncProgress",
  GET_FEATURES: "getfeatures",
  GET_FEATURES_RESULT: "getFeaturesResult",
  GET_FRAMEWORKS: "getframeworks",
  GET_FRAMEWORKS_RESULT: "getFrameworksResult",
  GET_PAGES: "getpages",
  GET_PAGES_RESULT: "getPagesResult",
  GET_PROJECT_TYPES: "getprojecttypes",
  GET_PROJECT_TYPES_RESULT: "getProjectTypesResult",
  GENERATE: "generate",
  GENERATE_RESULT: "generateResult",
  GENERATE_RESULT: "generateProgress",
  WINDOWS_PLATFORM_VERSION: "win32",
  SYNC_COMMAND_PREFIX: "sync",
  GET_ALL_LICENSES_COMMAND_PREFIX: "getalllicences",
  GET_ALL_LICENSES_COMPLETE_STATE: "getAllLicencesResult",
  PRODUCTION_PATH_TO_TEMPLATES: "..",
  DEVELOPMENT_PATH_TO_TEMPLATES: "../../../../..",
  MAX_SYNC_REQUEST_ATTEMPTS: 51,
  SYNC_RETRY_WAIT_TIME: 250,
};