// AutolinkedNativeModules.g.cs contents generated by "react-native autolink-windows"

using System.Collections.Generic;

// Namespaces from @react-native-async-storage/async-storage
using ReactNativeAsyncStorage;

namespace Microsoft.ReactNative.Managed
{
    internal static class AutolinkedNativeModules
    {
        internal static void RegisterAutolinkedNativeModulePackages(IList<IReactPackageProvider> packageProviders)
        { 
            // IReactPackageProviders from @react-native-async-storage/async-storage
            packageProviders.Add(new ReactNativeAsyncStorage.ReactPackageProvider());
        }
    }
}
