export enum CONFIG_TYPEKEYS {
  SET_PREVIEW_STATUS = "WTS/config/SET_PREVIEW_STATUS",
  RESET_WIZARD = "WTS/config/RESET_WIZARD",
  SET_PLATFORM = "WTS/config/SET_PLATFORM",
  SET_PROJECT_PATH_VALIDATION = "WTS/config/SET_PROJECT_PATH_VALIDATION",
  SET_VALIDATIONS = "WTS/config/SET_VALIDATIONS",
  GET_TEMPLATE_INFO = "WTS/GET_TEMPLATE_INFO",
  LOAD = "WTS/config/LOAD",
}
