export enum USERSELECTION_TYPEKEYS {
  SELECT_FRONTEND_FRAMEWORK = "WTS/user_selection/SELECT_FRONTEND_FRAMEWORK",
  SELECT_BACKEND_FRAMEWORK = "WTS/user_selection/SELECT_BACKEND_FRAMEWORK",
  SELECT_PROJECT_TYPE = "WTS/user_selection/SELECT_PROJECT_TYPE",
  SELECT_PAGES = "WTS/user_selection/SELECT_PAGES",
  SELECT_PAGE = "WTS/user_selection/SELECT_PAGE",
  SELECT_WEB_APP = "WTS/user_selection/SELECT_WEB_APP",
  SET_PROJECT_NAME = "WTS/user_selection/SET_PROJECT_NAME",
  SET_OUTPUT_PATH = "WTS/user_selection/UPDATE_PROJECT_PATH"
}
