
export enum TEMPLATES_TYPEKEYS {
  SET_PAGES_OPTIONS = "WTS/templates/SET_PAGES_OPTIONS",
  SET_PAGES_OPTIONS_SUCCESS = "WTS/templates/SET_PAGES_OPTIONS_SUCCESS",
  SET_FRONTEND_FRAMEWORKS = "WTS/templates/SET_FRONTEND_FRAMEWORKS",
  SET_BACKEND_FRAMEWORKS = "WTS/templates/SET_BACKEND_FRAMEWORKS",
  SET_PROJECT_TYPES = "WTS/templates/SET_PROJECT_TYPES",
  SET_ROUTES = "WTS/templates/SET_ROUTES",
  UPDATE_FRAMEWORK = "WTS/templates/UPDATE_FRAMEWORK",
  SET_FEATURES = "WTS/templates/SET_FEATURES"
}