export enum WIZARD_INFO_TYPEKEYS {
  GET_TEMPLATE_INFO = "WTS/GET_TEMPLATE_INFO",
  SET_VISITED_WIZARD_PAGE = "WTS/wizardNavigation/SET_VISITED_WIZARD_PAGE",
  RESET_VISITED_WIZARD_PAGE = "WTS/wizardNavigation/RESET_VISITED_WIZARD_PAGE",
  SET_PAGE_WIZARD_PAGE = "WTS/wizardNavigation/SET_PAGE_WIZARD_PAGE",
  SET_DETAILS_PAGE_INFO = "WTS/details/SET_DETAILS_PAGE_INFO",
  UPDATE_TEMPLATE_GENERATION_STATUS_MESSAGE = "WTS/postgen/UPDATE_TEMPLATE_GENERATION_STATUS_MESSAGE",
  UPDATE_TEMPLATE_GENERATION_STATUS = "WTS/postgen/UPDATE_TEMPLATE_GENERATION_STATUS",
  RESET_WIZARD = "RESET_WIZARD",
  UPDATE_DEPENDENCY_INFO = "WTS/dependency/UPDATE_DEPENDENCY_INFO",
  UPDATE_CREATE_PROJECT_BUTTON = "UPDATE_CREATE_PROJECT_BUTTON",
  ENABLE_QUICK_START = "ENABLE_QUICK_START"
}

export enum TEMPLATES_TYPEKEYS {
  GET_VSCODE_API = "WTS/vscode/GET_VSCODE_API",
  GET_PAGES_OPTIONS = "WTS/templates/GET_PAGES_OPTIONS",
  GET_PAGES_OPTIONS_SUCCESS = "WTS/templates/GET_PAGES_OPTIONS_SUCCESS",
  GET_WEB_APP_OPTIONS = "WTS/templates/GET_WEB_APP_OPTIONS",
  GET_WEB_APP_OPTIONS_SUCCESS = "WTS/templates/GET_WEB_APP_OPTIONS_SUCCESS",
  GET_FRONTEND_FRAMEWORKS = "WTS/templates/GET_FRONTEND_FRAMEWORKS",
  SET_FRONTEND_FRAMEWORKS = "WTS/templates/SET_FRONTEND_FRAMEWORKS",
  GET_BACKEND_FRAMEWORKS = "WTS/templates/GET_BACKEND_FRAMEWORKS",
  SET_PREVIEW_STATUS = "WTS/templates/SET_PREVIEW_STATUS",
  SET_BACKEND_FRAMEWORKS = "WTS/templates/SET_BACKEND_FRAMEWORKS",
  UPDATE_FRAMEWORK = "WTS/templates/UPDATE_FRAMEWORK",
  LOAD_WIZARD_CONTENT = "WTS/templates/LOAD_WIZARD_CONTENT"
}
